/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainTrainIdRouteImport } from './routes/train/$trainId'
import { Route as TilesSplatRouteImport } from './routes/tiles/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainTrainIdRoute = TrainTrainIdRouteImport.update({
  id: '/train/$trainId',
  path: '/train/$trainId',
  getParentRoute: () => rootRouteImport,
} as any)
const TilesSplatRoute = TilesSplatRouteImport.update({
  id: '/tiles/$',
  path: '/tiles/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tiles/$': typeof TilesSplatRoute
  '/train/$trainId': typeof TrainTrainIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tiles/$': typeof TilesSplatRoute
  '/train/$trainId': typeof TrainTrainIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tiles/$': typeof TilesSplatRoute
  '/train/$trainId': typeof TrainTrainIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tiles/$' | '/train/$trainId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tiles/$' | '/train/$trainId'
  id: '__root__' | '/' | '/tiles/$' | '/train/$trainId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TilesSplatRoute: typeof TilesSplatRoute
  TrainTrainIdRoute: typeof TrainTrainIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/$trainId': {
      id: '/train/$trainId'
      path: '/train/$trainId'
      fullPath: '/train/$trainId'
      preLoaderRoute: typeof TrainTrainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiles/$': {
      id: '/tiles/$'
      path: '/tiles/$'
      fullPath: '/tiles/$'
      preLoaderRoute: typeof TilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TilesSplatRoute: TilesSplatRoute,
  TrainTrainIdRoute: TrainTrainIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
