/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GtfsRouteImport } from './routes/gtfs'
import { Route as MapRouteImport } from './routes/_map'
import { Route as MapIndexRouteImport } from './routes/_map/index'
import { Route as GtfsRtFeedRouteImport } from './routes/gtfs-rt/$feed'
import { Route as MapTrainTrainIdRouteImport } from './routes/_map/train/$trainId'

const GtfsRoute = GtfsRouteImport.update({
  id: '/gtfs',
  path: '/gtfs',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/_map',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MapRoute,
} as any)
const GtfsRtFeedRoute = GtfsRtFeedRouteImport.update({
  id: '/gtfs-rt/$feed',
  path: '/gtfs-rt/$feed',
  getParentRoute: () => rootRouteImport,
} as any)
const MapTrainTrainIdRoute = MapTrainTrainIdRouteImport.update({
  id: '/train/$trainId',
  path: '/train/$trainId',
  getParentRoute: () => MapRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MapIndexRoute
  '/gtfs': typeof GtfsRoute
  '/gtfs-rt/$feed': typeof GtfsRtFeedRoute
  '/train/$trainId': typeof MapTrainTrainIdRoute
}
export interface FileRoutesByTo {
  '/gtfs': typeof GtfsRoute
  '/gtfs-rt/$feed': typeof GtfsRtFeedRoute
  '/': typeof MapIndexRoute
  '/train/$trainId': typeof MapTrainTrainIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_map': typeof MapRouteWithChildren
  '/gtfs': typeof GtfsRoute
  '/gtfs-rt/$feed': typeof GtfsRtFeedRoute
  '/_map/': typeof MapIndexRoute
  '/_map/train/$trainId': typeof MapTrainTrainIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gtfs' | '/gtfs-rt/$feed' | '/train/$trainId'
  fileRoutesByTo: FileRoutesByTo
  to: '/gtfs' | '/gtfs-rt/$feed' | '/' | '/train/$trainId'
  id:
    | '__root__'
    | '/_map'
    | '/gtfs'
    | '/gtfs-rt/$feed'
    | '/_map/'
    | '/_map/train/$trainId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MapRoute: typeof MapRouteWithChildren
  GtfsRoute: typeof GtfsRoute
  GtfsRtFeedRoute: typeof GtfsRtFeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gtfs': {
      id: '/gtfs'
      path: '/gtfs'
      fullPath: '/gtfs'
      preLoaderRoute: typeof GtfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_map': {
      id: '/_map'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_map/': {
      id: '/_map/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof MapRoute
    }
    '/gtfs-rt/$feed': {
      id: '/gtfs-rt/$feed'
      path: '/gtfs-rt/$feed'
      fullPath: '/gtfs-rt/$feed'
      preLoaderRoute: typeof GtfsRtFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_map/train/$trainId': {
      id: '/_map/train/$trainId'
      path: '/train/$trainId'
      fullPath: '/train/$trainId'
      preLoaderRoute: typeof MapTrainTrainIdRouteImport
      parentRoute: typeof MapRoute
    }
  }
}

interface MapRouteChildren {
  MapIndexRoute: typeof MapIndexRoute
  MapTrainTrainIdRoute: typeof MapTrainTrainIdRoute
}

const MapRouteChildren: MapRouteChildren = {
  MapIndexRoute: MapIndexRoute,
  MapTrainTrainIdRoute: MapTrainTrainIdRoute,
}

const MapRouteWithChildren = MapRoute._addFileChildren(MapRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MapRoute: MapRouteWithChildren,
  GtfsRoute: GtfsRoute,
  GtfsRtFeedRoute: GtfsRtFeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
